name: test

on: workflow_dispatch

jobs:
  temp_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
            - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    container:
      image: python:3.11-buster

    steps:

      - name: Check DB connection
        run: |
          ls -la
#          pip install pipenv
#          pipenv install --deploy --system --dev
#          python -m connection_test
